name: "SkillNest IAC"
on:
  push:
    branches:
      - main
      - stage
    paths:
      - infrastructure/**
  pull_request:
    branches:
      - main
    paths:
      - infrastructure/**
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
  AWS_REGION: us-east-1
  EKS_CLUSTER: gitops-eks

jobs:
  terraform:
    name: "Apply TF code changes"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup TF with version on the runner
        uses: hashicorp/setup-terraform@v2

      - name: TF init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: TF format
        id: fmt
        run: terraform fmt -check

      - name: TF validate
        id: validate
        run: terraform validate

      - name: TF plan
        id: plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: TF plan status
        if: steps.validate.outcome == 'failure'
        run: exit 1