name: "SkillNest IAC"
on:
  push:
    branches:
      - main
      - stage
    paths:
      - infrastructure/**
  pull_request:
    branches:
      - main
    paths:
      - infrastructure/**
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
  AWS_REGION: us-east-1
  EKS_CLUSTER: gitops-eks

jobs:
  terraform:
    name: "Apply TF code changes"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ./infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup TF with version on the runner
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::911893329503:role/skillnest-infra-role
          aws-region: us-east-1

      - name: TF init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: TF format
        id: fmt
        run: terraform fmt -check

      - name: TF validate
        id: validate
        run: terraform validate

      - name: TF plan
        id: plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: TF plan status
        if: steps.validate.outcome == 'failure'
        run: exit 1

      - name: TF apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false -parallelism=1 planfile

      # - name: Get Kube config file
      #   id: getconfig
      #   if: steps.apply.outcome == 'success'
      #   run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      # - name: Install Ingress controller
      #   if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
      #   run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml